# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateQSeq <- function(m, deg_seq, model) {
    .Call(`_multigraphr_calculateQSeq`, m, deg_seq, model)
}

#'@export
getEdgeMultipSeq <- function(deg_seq) {
    .Call(`_multigraphr_getEdgeMultipSeq`, deg_seq)
}

